#ifndef OPERATION_ENUM_H
#define OPERATION_ENUM_H

enum OperationEnum {
    NO_OPERATION = 0,
    SORT_TECHNIQUE_ONE = 1,
    SORT_TECHNIQUE_TWO = 2,
    SORT_TECHNIQUE_ONE_IMPROVED = 3,
    SORT_TECHNIQUE_TWO_IMPROVED = 4,
    SORT_COMPARE = 5,
    SORT_COMPARE_IMPROVED = 6,
    SEARCH_TECHNIQUE_ONE = 7,
    SEARCH_TECHNIQUE_ONE_IMPROVED = 8,
    SEARCH_TECHNIQUE_TWO = 9,
    SEARCH_TECHNIQUE_TWO_IMPROVED = 10,
    SEARCH_COMPARE = 11,
    SEARCH_COMPARE_IMPROVED = 12,
    ADDITIONAL_ONE = 13,
    ADDITIONAL_TWO = 14,
    ADDITIONAL_THREE = 15,
    DATA_RELOAD = 99,
};

#endif
